import type { ScanGithubAccess } from "./githubAccess.js";
import type { OperatorScopeAttempt, OperatorUsage } from "./operatorContracts.js";
import { OperatorPublicationService } from "./operatorPublication.js";
import { OperatorStore } from "./operatorStore.js";

export interface OperatorScopeDto { scopeId: string; parentScopeId?: string; name: string; state: string; stale: boolean; explanation?: unknown; explanationVersionId?: string; diagramError?: string; attempts?: OperatorScopeAttempt[]; }
export interface OperatorWorkflowJob { kind: "run" | "retry" | "refresh"; runId: string; draftRevisionId?: string; scopeIds?: string[]; githubAccess: ScanGithubAccess; }
export interface OperatorWorkflowOptions { store: OperatorStore; publications: OperatorPublicationService; enqueue: (job: OperatorWorkflowJob) => void | Promise<void>; }

/** Safe controller façade: draft data stays here, never under public /scan routes. */
export class OperatorWorkflow {
  constructor(private readonly options: OperatorWorkflowOptions) {}
  runDetail(runId: string) { const state = this.options.store.snapshot(); const run = state.runs.find(value => value.runId === runId); if (!run) return undefined; return { run, draft: run.draftRevisionId ? state.drafts.find(value => value.draftRevisionId === run.draftRevisionId) : undefined, attempts: run.draftRevisionId ? state.attempts.filter(value => value.draftRevisionId === run.draftRevisionId).slice(-100) : [], events: state.events.filter(value => value.runId === runId).slice(-100), usage: usage(run.draftRevisionId ? state.attempts.filter(value => value.draftRevisionId === run.draftRevisionId) : []) }; }
  draftDetail(draftRevisionId: string) { const state = this.options.store.snapshot(); const draft = state.drafts.find(value => value.draftRevisionId === draftRevisionId); if (!draft) return undefined; const run = state.runs.find(value => value.runId === draft.runId)!; const attempts = state.attempts.filter(value => value.draftRevisionId === draftRevisionId); const scopes: OperatorScopeDto[] = [...new Set(attempts.map(value => value.scopeId))].map(scopeId => { const rows = attempts.filter(value => value.scopeId === scopeId); const latest = rows.at(-1)!; const explanation = this.options.store.getAcceptedExplanation(draftRevisionId, scopeId); const content = explanation?.content as { summary?: unknown; diagramError?: unknown } | undefined; return { scopeId, name: scopeId, state: latest.state, stale: Boolean(latest.stale), ...(explanation ? { explanation: content?.summary ?? content, explanationVersionId: explanation.explanationVersionId } : {}), ...(typeof content?.diagramError === "string" ? { diagramError: content.diagramError } : {}), attempts: rows }; }); return { draft, source: run.source, scopes, usage: usage(attempts), ...(this.options.publications.currentPublication(draft.repositoryId) ? { currentPublicationVersionId: this.options.publications.currentPublication(draft.repositoryId)!.versionId } : {}) }; }
  bundle(draftRevisionId: string): Buffer | undefined { const detail = this.draftDetail(draftRevisionId); return detail ? this.options.store.readArtifactFile(detail.draft.artifactRevisionId, "snapshot.json") : undefined; }
  async enqueue(job: OperatorWorkflowJob): Promise<void> { await this.options.enqueue(job); }
}
function usage(attempts: OperatorScopeAttempt[]): OperatorUsage & { costStatus: "measured" | "estimated" | "unknown" } { const rows = attempts.map(value => value.usage).filter((value): value is OperatorUsage => Boolean(value)); const measuredCostUsd = rows.reduce((total, value) => total + (value.measuredCostUsd ?? 0), 0); const estimatedCostUsd = rows.reduce((total, value) => total + (value.estimatedCostUsd ?? 0), 0); return { inputTokens: rows.reduce((total, value) => total + (value.inputTokens ?? 0), 0), outputTokens: rows.reduce((total, value) => total + (value.outputTokens ?? 0), 0), ...(measuredCostUsd ? { measuredCostUsd } : {}), ...(estimatedCostUsd ? { estimatedCostUsd } : {}), costStatus: measuredCostUsd ? "measured" : estimatedCostUsd ? "estimated" : "unknown" }; }
